version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./apps/api
      dockerfile: ../../docker/api.Dockerfile
    env_file: ./apps/api/.env.local
    depends_on:
      db:
        condition: service_healthy
    ports: ["3000:3000"]
    command: ["npm","run","dev"]
    volumes:
      - ./apps/api:/app

  adminer:
    image: adminer
    restart: always
    ports: ["8080:8080"]

volumes:
  db_data:
